AWSTemplateFormatVersion: "2010-09-09"
Description: Create an AWS Glue crawler

Parameters:
  CityDataS3BucketName:
    Type: String
    Default: "s3://com-in-context-data-load-staging"

Resources:
  CityDataGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: city-data-db
        Description: Database for CityData

#  CityDataGlueTable:
#    Type: AWS::Glue::Table
#    Properties:
#      CatalogId: !Ref AWS::AccountId
#      DatabaseName: !Ref CityDataGlueDatabase
#      TableInput:
#        Name: city-data-table
#        TableType: EXTERNAL_TABLE
#        Parameters:
#          classification: csv
#        StorageDescriptor:
#          Location: !Sub "${CityDataS3BucketName}/data/"
#          InputFormat: org.apache.hadoop.mapred.TextInputFormat
#          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
#          Compressed: false
#          SerdeInfo:
#            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
#            Parameters:
#              separatorChar: ","
#          Columns:
#            - Name: id
#              Type: string
#            - Name: country
#              Type: string
#            - Name: state
#              Type: string
#            - Name: city
#              Type: string

  CityDataGlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CityDataCrawlerRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueCrawlerS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource: "*"
#                  - arn:aws:s3:::com-in-context-data-load-staging
#                  - arn:aws:s3:::com-in-context-data-load-staging/*


  CityDataCSVClassifier:
    Type: AWS::Glue::Classifier
    Properties:
      CsvClassifier:
        Name: CityDataCSVClassifier
        Delimiter: ","
        QuoteSymbol: "\""
        ContainsHeader: "PRESENT" # Other options: ABSENT, UNKNOWN
        # Optional properties for specific scenarios
        # AllowSingleColumn: true | false
        # DisableGlobalHeaders: true | false
        # HeaderDerivedCols: integer

  CityDataGlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: CityDataCrawler
      Role: !GetAtt CityDataGlueCrawlerRole.Arn
      DatabaseName: !Ref CityDataGlueDatabase
      Classifiers:
        - !Ref CityDataCSVClassifier
      Targets:
        S3Targets:
          - Path: !Sub "${CityDataS3BucketName}/data/"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG

  CityDataAthenaNamedQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: !Ref CityDataGlueDatabase
      Description: "Return the cities"
      Name: "ReturnCities"
      QueryString: >
        SELECT * FROM "data" limit 10;
      WorkGroup: "primary" # Optional: specify a workgroup if needed

Outputs:
  CrawlerName:
    Value: !Ref CityDataGlueCrawler
    Description: Name of the created Glue crawler

  DatabaseName:
    Value: !Ref CityDataGlueDatabase
    Description: Name of the created database

  AthenaNamedQueryId:
    Description: "The unique ID of the created Athena Named Query"
    Value: !Ref CityDataAthenaNamedQuery

#  TableName:
#    Value: !Ref CityDataGlueTable
#    Description: Name of the created table
