AWSTemplateFormatVersion: "2010-09-09"
Description: Create an AWS Glue crawler

Resources:
  CityDataS3BucketName:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com-in-context-data-load-staging

  CityDataGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: city-data-db
        Description: Database for the data

  CityDataGlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CityDataCrawlerRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueCrawlerS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !GetAtt CityDataS3BucketName.Arn
                  - !Sub "${CityDataS3BucketName.Arn}/*"

  CityDataCSVClassifier:
    Type: AWS::Glue::Classifier
    Properties:
      CsvClassifier:
        Name: CityDataCSVClassifier
        Delimiter: ","
        QuoteSymbol: "\""
        ContainsHeader: "PRESENT" # Other options: ABSENT, UNKNOWN
        # Optional properties for specific scenarios
        # AllowSingleColumn: true | false
        # DisableGlobalHeaders: true | false
        # HeaderDerivedCols: integer

  CityDataGlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: CityDataCrawler
      Role: !GetAtt CityDataGlueCrawlerRole.Arn
      DatabaseName: !Ref CityDataGlueDatabase
      Classifiers:
        - !Ref CityDataCSVClassifier
      Targets:
        S3Targets:
          - Path: !Sub "${CityDataS3BucketName}/city-data/"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: city-data-etl-job
      Description: "Replace nulls with 'n/a'"
      Role: !GetAtt CityDataGlueCrawlerRole.Arn
      GlueVersion: "4.0"
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${CityDataS3BucketName}/scripts/city_etl.py"
        PythonVersion: "3.9"
      DefaultArguments:
        --job-bookmark-option: job-bookmark-enable
        --TempDir: !Sub "s3://${CityDataS3BucketName}/temp/"
        --enable-continuous-cloudwatch-log: "true"
        "--BUCKET_NAME": !Sub "s3://${CityDataS3BucketName}"
        "--DATA_FILE_LOCATION": "city-data"
        "--DATA_FILE_NAME": "CityData.csv"
        "--PROCESSED_DATA_LOCATION": "processed"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Timeout: 30
      MaxRetries: 0
      MaxCapacity: 1

  CityDataAthenaNamedQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: !Ref CityDataGlueDatabase
      Description: "Return the cities"
      Name: "ReturnCities"
      QueryString: >
        SELECT * FROM "city_data";
      WorkGroup: "primary" # Optional: specify a workgroup if needed

  ProcessedCityDataGlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CityDataGlueDatabase
      TableInput:
        Name: city-data-processed
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          EXTERNAL: true
        StorageDescriptor:
          Location: !Sub "s3://${CityDataS3BucketName}/processed/"
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Compressed: false
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Columns:
            - Name: id
              Type: string
            - Name: country
              Type: string
            - Name: state
              Type: string
            - Name: city
              Type: string

  ProcessedCityDataAthenaNamedQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: !Ref CityDataGlueDatabase
      Description: "Return processed cities"
      Name: "ReturnProcessedCities"
      QueryString: >
        SELECT * FROM "city-data-processed";
      WorkGroup: "primary" # Optional: specify a workgroup if needed

Outputs:
  CrawlerName:
    Value: !Ref CityDataGlueCrawler
    Description: Name of the created Glue crawler

  DatabaseName:
    Value: !Ref CityDataGlueDatabase
    Description: Name of the created database

  GlueETLJob:
    Description: "Glue ETL"
    Value: !Ref GlueJob

#  TableName:
#    Value: !Ref CityDataGlueTable
#    Description: Name of the created table
